export default {
  pages: [
    'pages/home/index',
    'pages/index/index',
    'pages/profile/index',
    'pages/settings/index',
    'pages/search/index',
    "pages/feedback/index", 
    "pages/map/index", 
    "pages/history/index", 
    "pages/findLatest/index",
    "pages/collect/index", 
    "pages/place/index",
    'pages/my/index',
    'pages/reminderIndex/index',
    'pages/reminder/index',
    'pages/recode/index',
    'pages/addRecode/index',
    'pages/calendar/index',
    'pages/intimate/index',
    'pages/userinfo/index',
    'pages/signin/index/index',
    'pages/points/recode/index',
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#fff',
    navigationBarTitleText: 'WeChat',
    navigationBarTextStyle: 'black'
  },
  lazyCodeLoading: "requiredComponents",
}
